// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloDatosAcceso.Modelo;
using ModeloDatosAcceso.ModeloNegocio;

namespace ModeloDatosAcceso.ModeloNegocio.Migrations
{
    [DbContext(typeof(ModeloEntityFrameworkEjercicioClaroV))]
    [Migration("20180628235152_MigracionParaDBEjercicioClaroV")]
    partial class MigracionParaDBEjercicioClaroV
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("ModeloDatosAcceso.ModeloNegocio.DetalleLista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AlbumId");

                    b.Property<string>("AlbumName");

                    b.Property<string>("Artist");

                    b.Property<string>("ArtistId");

                    b.Property<string>("Artists");

                    b.Property<string>("Duration");

                    b.Property<long>("DurationInSeconds");

                    b.Property<string>("Image");

                    b.Property<string>("InternalId");

                    b.Property<string>("ListSourceType");

                    b.Property<long>("ListaId");

                    b.Property<string>("Name");

                    b.Property<long>("SongSourceType");

                    b.Property<long>("TrackNumber");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("detallesLista");
                });

            modelBuilder.Entity("ModeloDatosAcceso.ModeloNegocio.Listas", b =>
                {
                    b.Property<long>("ListaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Image");

                    b.Property<bool>("IsFollowing");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("ListaId");

                    b.ToTable("listas");
                });
#pragma warning restore 612, 618
        }
    }
}
